from exceptions.system.fatal_error import FatalError
